# Generated by Django 4.2.13 on 2024-05-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_user_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='column_number',
        ),
        migrations.AddField(
            model_name='points',
            name='column_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='points',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='points',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
    ]
