# Generated by Django 4.2.13 on 2024-05-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_points_column_number_points_column_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
