# Generated by Django 4.2.13 on 2024-05-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_points_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='point',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
