# Generated by Django 4.2.13 on 2024-05-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_points_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='courses',
        ),
    ]
